let MINIBOSSES: IMiniBoss[] = [SIMPLE_BOSS, TWO_PHASE_BOSS, LICH_KING, NUNU, ZARGON, HIPOPOTAMO_DO_MAL, MAE_MOSCA, IRMA_DE_CRISTAL];

let BOSS_NAME_FOR_CONFIG = {
  SIMPLE_BOSS: 0,
  TWO_PHASE_BOSS: 1,
  LICH_KING: 2,
  NUNU: 3,
  ZARGON: 4,
  HIPOPOTAMO_DO_MAL: 5,
  MAE_MOSCA: 6,
  IRMA_DE_CRISTAL: 7
};
